import SavedData
from PyQt5 import QtCore, QtGui, QtWidgets
from sympy.integrals.meijerint_doc import category

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 494)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navBar = QtWidgets.QFrame(self.centralwidget)
        self.navBar.setMinimumSize(QtCore.QSize(0, 50))
        self.navBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.navBar.setStyleSheet("background-color: rgb(85, 85, 255)")
        self.navBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBar.setObjectName("navBar")
        self.verticalLayout.addWidget(self.navBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.HeadTitle = QtWidgets.QLabel(self.centralwidget)
        self.HeadTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.HeadTitle.setFont(font)
        self.HeadTitle.setObjectName("HeadTitle")
        self.verticalLayout.addWidget(self.HeadTitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.NameandCategoryLayout = QtWidgets.QHBoxLayout()
        self.NameandCategoryLayout.setContentsMargins(30, 5, 30, 5)
        self.NameandCategoryLayout.setSpacing(0)
        self.NameandCategoryLayout.setObjectName("NameandCategoryLayout")
        self.ItemTitle = QtWidgets.QLabel(self.centralwidget)
        self.ItemTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.ItemTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ItemTitle.setFont(font)
        self.ItemTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.ItemTitle.setObjectName("ItemTitle")
        self.NameandCategoryLayout.addWidget(self.ItemTitle)
        self.CategoryTitle = QtWidgets.QLabel(self.centralwidget)
        self.CategoryTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CategoryTitle.setFont(font)
        self.CategoryTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.CategoryTitle.setObjectName("CategoryTitle")
        self.NameandCategoryLayout.addWidget(self.CategoryTitle)
        self.verticalLayout.addLayout(self.NameandCategoryLayout)
        self.ItemandCategoryLayout = QtWidgets.QHBoxLayout()
        self.ItemandCategoryLayout.setContentsMargins(30, -1, 30, 10)
        self.ItemandCategoryLayout.setObjectName("ItemandCategoryLayout")
        self.ItemInputBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemInputBox.sizePolicy().hasHeightForWidth())
        self.ItemInputBox.setSizePolicy(sizePolicy)
        self.ItemInputBox.setMinimumSize(QtCore.QSize(0, 40))
        self.ItemInputBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ItemInputBox.setFont(font)
        self.ItemInputBox.setStyleSheet("padding-left: 10px")
        self.ItemInputBox.setObjectName("ItemInputBox")
        self.ItemandCategoryLayout.addWidget(self.ItemInputBox)
        self.CategoryBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoryBox.sizePolicy().hasHeightForWidth())
        self.CategoryBox.setSizePolicy(sizePolicy)
        self.CategoryBox.setMinimumSize(QtCore.QSize(0, 40))
        self.CategoryBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CategoryBox.setFont(font)
        self.CategoryBox.setStyleSheet("padding-left: 10px")
        self.CategoryBox.setObjectName("CategoryBox")
        self.CategoryBox.addItem("")
        self.CategoryBox.addItem("")
        self.CategoryBox.addItem("")
        self.CategoryBox.addItem("")
        self.CategoryBox.addItem("")
        self.ItemandCategoryLayout.addWidget(self.CategoryBox)
        self.ItemandCategoryLayout.setStretch(0, 1)
        self.ItemandCategoryLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.ItemandCategoryLayout)
        self.PriceandCurrencyLayout_2 = QtWidgets.QHBoxLayout()
        self.PriceandCurrencyLayout_2.setContentsMargins(30, 5, 30, 5)
        self.PriceandCurrencyLayout_2.setSpacing(0)
        self.PriceandCurrencyLayout_2.setObjectName("PriceandCurrencyLayout_2")
        self.PriceTitle = QtWidgets.QLabel(self.centralwidget)
        self.PriceTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PriceTitle.setFont(font)
        self.PriceTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.PriceTitle.setObjectName("PriceTitle")
        self.PriceandCurrencyLayout_2.addWidget(self.PriceTitle)
        self.CurrencyTitle = QtWidgets.QLabel(self.centralwidget)
        self.CurrencyTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CurrencyTitle.setFont(font)
        self.CurrencyTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.CurrencyTitle.setObjectName("CurrencyTitle")
        self.PriceandCurrencyLayout_2.addWidget(self.CurrencyTitle)
        self.verticalLayout.addLayout(self.PriceandCurrencyLayout_2)
        self.PriceandCurrencyLayout = QtWidgets.QHBoxLayout()
        self.PriceandCurrencyLayout.setContentsMargins(30, -1, 30, 10)
        self.PriceandCurrencyLayout.setObjectName("PriceandCurrencyLayout")
        self.PriceBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceBox.sizePolicy().hasHeightForWidth())
        self.PriceBox.setSizePolicy(sizePolicy)
        self.PriceBox.setMinimumSize(QtCore.QSize(0, 40))
        self.PriceBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PriceBox.setFont(font)
        self.PriceBox.setStyleSheet("padding-left: 10px")
        self.PriceBox.setMaximum(999999)
        self.PriceBox.setObjectName("PriceBox")
        self.PriceandCurrencyLayout.addWidget(self.PriceBox)
        self.CurrencyBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrencyBox.sizePolicy().hasHeightForWidth())
        self.CurrencyBox.setSizePolicy(sizePolicy)
        self.CurrencyBox.setMinimumSize(QtCore.QSize(0, 40))
        self.CurrencyBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CurrencyBox.setFont(font)
        self.CurrencyBox.setStyleSheet("padding-left: 10px")
        self.CurrencyBox.setObjectName("CurrencyBox")
        self.CurrencyBox.addItem("")
        self.CurrencyBox.addItem("")
        self.CurrencyBox.addItem("")
        self.CurrencyBox.addItem("")
        self.PriceandCurrencyLayout.addWidget(self.CurrencyBox)
        self.verticalLayout.addLayout(self.PriceandCurrencyLayout)
        self.DateandTimeLayout_2 = QtWidgets.QHBoxLayout()
        self.DateandTimeLayout_2.setContentsMargins(30, 5, 30, 5)
        self.DateandTimeLayout_2.setSpacing(0)
        self.DateandTimeLayout_2.setObjectName("DateandTimeLayout_2")
        self.DateTitle = QtWidgets.QLabel(self.centralwidget)
        self.DateTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DateTitle.setFont(font)
        self.DateTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.DateTitle.setObjectName("DateTitle")
        self.DateandTimeLayout_2.addWidget(self.DateTitle)
        self.TimeTitle = QtWidgets.QLabel(self.centralwidget)
        self.TimeTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TimeTitle.setFont(font)
        self.TimeTitle.setStyleSheet("color: rgb(117, 117, 117);")
        self.TimeTitle.setObjectName("TimeTitle")
        self.DateandTimeLayout_2.addWidget(self.TimeTitle)
        self.verticalLayout.addLayout(self.DateandTimeLayout_2)
        self.DateandTimeLayout = QtWidgets.QHBoxLayout()
        self.DateandTimeLayout.setContentsMargins(30, -1, 30, 10)
        self.DateandTimeLayout.setObjectName("DateandTimeLayout")
        self.DateBox = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateBox.sizePolicy().hasHeightForWidth())
        self.DateBox.setSizePolicy(sizePolicy)
        self.DateBox.setMinimumSize(QtCore.QSize(0, 40))
        self.DateBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DateBox.setFont(font)
        self.DateBox.setStyleSheet("padding-left: 10px")
        self.DateBox.setObjectName("DateBox")
        self.DateandTimeLayout.addWidget(self.DateBox)
        self.TimeBox = QtWidgets.QTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeBox.sizePolicy().hasHeightForWidth())
        self.TimeBox.setSizePolicy(sizePolicy)
        self.TimeBox.setMinimumSize(QtCore.QSize(0, 40))
        self.TimeBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeBox.setFont(font)
        self.TimeBox.setStyleSheet("padding-left: 10px")
        self.TimeBox.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2222, 1, 1), QtCore.QTime(23, 59, 59)))
        self.TimeBox.setObjectName("TimeBox")
        self.DateandTimeLayout.addWidget(self.TimeBox)
        self.verticalLayout.addLayout(self.DateandTimeLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.ButtonLayout = QtWidgets.QHBoxLayout()
        self.ButtonLayout.setObjectName("ButtonLayout")
        self.DoneButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoneButton.sizePolicy().hasHeightForWidth())
        self.DoneButton.setSizePolicy(sizePolicy)
        self.DoneButton.setMinimumSize(QtCore.QSize(100, 50))
        self.DoneButton.setMaximumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        # Done Button
        self.DoneButton.setFont(font)
        self.DoneButton.setStyleSheet("QPushButton {\n"
"    border-radius:3px;\n"
"    background-color: white;\n"
"transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"     color:white\n"
"}\n"
"")
        self.DoneButton.setFlat(False)
        self.DoneButton.setObjectName("DoneButton")
        self.DoneButton.clicked.connect(self.addPurchase)

        self.ButtonLayout.addWidget(self.DoneButton)
        self.verticalLayout.addLayout(self.ButtonLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expense Tracker"))
        self.HeadTitle.setText(_translate("MainWindow", "  Add Purchase"))
        self.ItemTitle.setText(_translate("MainWindow", "Item Name"))
        self.CategoryTitle.setText(_translate("MainWindow", "Item Category"))
        self.ItemInputBox.setPlaceholderText(_translate("MainWindow", "Enter item name"))
        self.CategoryBox.setPlaceholderText(_translate("MainWindow", "Choose item cetagory"))
        self.CategoryBox.setItemText(0, _translate("MainWindow", "Food"))
        self.CategoryBox.setItemText(1, _translate("MainWindow", "Transport"))
        self.CategoryBox.setItemText(2, _translate("MainWindow", "Bills"))
        self.CategoryBox.setItemText(3, _translate("MainWindow", "Clothes"))
        self.CategoryBox.setItemText(4, _translate("MainWindow", "Other"))
        self.PriceTitle.setText(_translate("MainWindow", "Price"))
        self.CurrencyTitle.setText(_translate("MainWindow", "Currency"))
        self.CurrencyBox.setItemText(0, _translate("MainWindow", "EGP"))
        self.CurrencyBox.setItemText(1, _translate("MainWindow", "USD"))
        self.CurrencyBox.setItemText(2, _translate("MainWindow", "EUR"))
        self.CurrencyBox.setItemText(3, _translate("MainWindow", "SAR"))
        self.DateTitle.setText(_translate("MainWindow", "Date"))
        self.TimeTitle.setText(_translate("MainWindow", "Time"))
        self.DoneButton.setText(_translate("MainWindow", "Done"))

    def addPurchase(self):
        itemName = self.ItemInputBox.text()
        category = self.CategoryBox.currentText()
        price = self.PriceBox.text()
        date = self.DateBox.date().toString("yyyy-MM-dd")
        time = self.TimeBox.time().toString("hh:mm")
        purchaseList = [itemName, category, price, date, time]
        SavedData.append_data(purchaseList)
        print(SavedData.load_data())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
